USE [master]
GO

/****** Object:  Database [Name_Generator]    Script Date: 10/3/2017 9:07:55 PM ******/
CREATE DATABASE [Name_Generator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Name_Generator', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Name_Generator.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Name_Generator_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Name_Generator_log.ldf' , SIZE = 1384448KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Name_Generator] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Name_Generator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Name_Generator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Name_Generator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Name_Generator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Name_Generator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Name_Generator] SET ARITHABORT OFF 
GO

ALTER DATABASE [Name_Generator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Name_Generator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Name_Generator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Name_Generator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Name_Generator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Name_Generator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Name_Generator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Name_Generator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Name_Generator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Name_Generator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Name_Generator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Name_Generator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Name_Generator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Name_Generator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Name_Generator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Name_Generator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Name_Generator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Name_Generator] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Name_Generator] SET  MULTI_USER 
GO

ALTER DATABASE [Name_Generator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Name_Generator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Name_Generator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Name_Generator] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Name_Generator] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Name_Generator] SET QUERY_STORE = OFF
GO

USE [Name_Generator]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Name_Generator] SET  READ_WRITE 
GO

